CREATE TABLE IF NOT EXISTS BOOK (
    BOOK_ID TEXT PRIMARY KEY,
    BOOK_NAME TEXT,
    BOOK_PRICE TEXT,
    BOOK_CAT TEXT
);

INSERT INTO BOOK(BOOK_ID, BOOK_NAME, BOOK_PRICE, BOOK_CAT)
VALUES
    ("201", "PYTHON BASICS", "450", "10"),
    ("202", "DATA STRUCTURES", "800", "11"),
    ("203", "WEB DEVELOPMENT", "650", "12"),
    ("204", "DATABASE SYSTEMS", "900", "13"),
    ("205", "COMPUTER NETWORKS", "1200", "14"),
    ("206", "OPERATING SYSTEM", "750", "15"),
    ("207", "JAVA PROGRAMMING", "1000", "16"),
    ("208", "C PROGRAMMING", "500", "10"),
    ("209", "MACHINE LEARNING", "1500", "17"),
    ("210", "CLOUD COMPUTING", "1100", "18");

-- Find the book with the lowest price
SELECT BOOK_NAME, BOOK_PRICE
FROM BOOK
WHERE BOOK_PRICE =
    (SELECT MIN(BOOK_PRICE) FROM BOOK);

-- Find the book with the highest price
SELECT BOOK_NAME, BOOK_PRICE
FROM BOOK
WHERE BOOK_PRICE =
    (SELECT MAX(BOOK_PRICE) FROM BOOK);
